// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Defines values for CardSuit.
const (
	CardSuitCLUBS CardSuit = "CLUBS"

	CardSuitDIAMONDS CardSuit = "DIAMONDS"

	CardSuitHEARTS CardSuit = "HEARTS"

	CardSuitSPADES CardSuit = "SPADES"
)

// Defines values for CardValue.
const (
	CardValueACE CardValue = "ACE"

	CardValueJACK CardValue = "JACK"

	CardValueKING CardValue = "KING"

	CardValueN10 CardValue = "10"

	CardValueN2 CardValue = "2"

	CardValueN3 CardValue = "3"

	CardValueN4 CardValue = "4"

	CardValueN5 CardValue = "5"

	CardValueN6 CardValue = "6"

	CardValueN7 CardValue = "7"

	CardValueN8 CardValue = "8"

	CardValueN9 CardValue = "9"

	CardValueQUEEN CardValue = "QUEEN"
)

// Card defines model for Card.
type Card struct {
	Code  *CardCode  `json:"code,omitempty"`
	Suit  *CardSuit  `json:"suit,omitempty"`
	Value *CardValue `json:"value,omitempty"`
}

// CardCode defines model for CardCode.
type CardCode string

// CardSuit defines model for CardSuit.
type CardSuit string

// CardValue defines model for CardValue.
type CardValue string

// Cards defines model for Cards.
type Cards struct {
	Cards *[]Card `json:"cards,omitempty"`
}

// DeckBrief defines model for DeckBrief.
type DeckBrief struct {
	DeckId    *openapi_types.UUID `json:"deck_id,omitempty"`
	Remaining *NumberOfCards      `json:"remaining,omitempty"`
	Shuffled  *bool               `json:"shuffled,omitempty"`
}

// DeckFull defines model for DeckFull.
type DeckFull struct {
	// Embedded struct due to allOf(#/components/schemas/DeckBrief)
	DeckBrief `yaml:",inline"`
	// Embedded struct due to allOf(#/components/schemas/Cards)
	Cards `yaml:",inline"`
}

// NumberOfCards defines model for NumberOfCards.
type NumberOfCards int32

// DeckId defines model for DeckId.
type DeckId openapi_types.UUID

// CreateDeckResponse defines model for CreateDeckResponse.
type CreateDeckResponse DeckBrief

// DrawCardsResponse defines model for DrawCardsResponse.
type DrawCardsResponse Cards

// OpenDeckResponse defines model for OpenDeckResponse.
type OpenDeckResponse DeckFull

// PostDecksParams defines parameters for PostDecks.
type PostDecksParams struct {
	Shuffled *bool       `json:"shuffled,omitempty"`
	Cards    *[]CardCode `json:"cards,omitempty"`
}

// PutDecksIdDrawParams defines parameters for PutDecksIdDraw.
type PutDecksIdDrawParams struct {
	Count NumberOfCards `json:"count"`
}
